# These are supported funding model platforms

github: [tranvuongquocdat]
buy_me_a_coffee: tranvuongqk

# Other platforms (uncomment if using)
# ko_fi: your-username
# patreon: your-username
# custom: ['https://your-custom-link.com']
