disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - identifier_name
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - nesting
  - multiple_closures_with_trailing_closure

included:
  - Sources

reporter: xcode
